spring:
  data:
    mongodb:
      uri: "mongodb://admin:password@localhost:27017/mongock-poc-db?authSource=admin"

####### Mongock Properties ###########
mongock:
  migration-scan-package: pl.walczak.jakub.mongodbmigrationspoc.dbmigrations
